import type {
  Expedition,
  ExpeditionDetailData,
  ExpeditionTerminalDetailItem,
  ExpeditionTerminalSummaryItem,
} from "./types";

export const todayExpeditionsMock: Expedition[] = [
  {
    id: 1,
    expeditionNumber: "EXP-2026-041",
    assignedTo: "Ian Tauzy",
    destination: "Madrid",
    sentDate: "2026-04-06",
    receivedDate: null,
    status: "en_transito",
  },
  {
    id: 2,
    expeditionNumber: "EXP-2026-042",
    assignedTo: "Alba Panato",
    destination: "Valencia",
    sentDate: "2026-04-06",
    receivedDate: "2026-04-06",
    status: "abierta",
  },
  {
    id: 3,
    expeditionNumber: "EXP-2026-043",
    assignedTo: "Marta Soler",
    destination: "Sevilla",
    sentDate: "2026-04-06",
    receivedDate: null,
    status: "en_transito",
  },
  {
    id: 4,
    expeditionNumber: "EXP-2026-044",
    assignedTo: "David Rico",
    destination: "Barcelona",
    sentDate: "2026-04-06",
    receivedDate: "2026-04-06",
    status: "recibida",
  },
  {
    id: 5,
    expeditionNumber: "EXP-2026-045",
    assignedTo: "Lucia Torres",
    destination: "Bilbao",
    sentDate: "2026-04-06",
    receivedDate: null,
    status: "abierta",
  },
  {
    id: 6,
    expeditionNumber: "EXP-2026-046",
    assignedTo: "Sergio Marin",
    destination: "Malaga",
    sentDate: "2026-04-06",
    receivedDate: null,
    status: "en_transito",
  },
  {
    id: 7,
    expeditionNumber: "EXP-2026-047",
    assignedTo: "Claudia Perez",
    destination: "Alicante",
    sentDate: "2026-04-06",
    receivedDate: "2026-04-06",
    status: "recibida",
  },
];

const terminalSummaryMock: ExpeditionTerminalSummaryItem[] = [
  { model: "IBM M57", entity: "10 - BP", quantity: 1 },
  { model: "IBM M82", entity: "10 - BP", quantity: 1 },
  { model: "ICT220 Contactless + Magic Box", entity: "10 - BP", quantity: 2 },
];

const terminalDetailsMock: ExpeditionTerminalDetailItem[] = [
  {
    id: 1,
    model: "IBM M57",
    entity: "BP",
    status: "Operativo",
    location: "Ubicacion de tpvs en transito",
    coverage: "",
    serialNumber: "1S6072WEDLMKZW10",
  },
  {
    id: 2,
    model: "IBM M82",
    entity: "BP",
    status: "Operativo",
    location: "Ubicacion de tpvs en transito",
    coverage: "",
    serialNumber: "1S2929A5754AADTB",
  },
  {
    id: 3,
    model: "ICT220 Contactless + Magic Box",
    entity: "BP",
    status: "Operativo",
    location: "Ubicacion de tpvs en transito",
    coverage: "",
    serialNumber: "14336CT23020767",
  },
  {
    id: 4,
    model: "ICT220 Contactless + Magic Box",
    entity: "BP",
    status: "Operativo",
    location: "Ubicacion de tpvs en transito",
    coverage: "REP LAB NECOMPLUS",
    serialNumber: "18307CT27050551",
  },
];

export const expeditionDetailsMock: Record<number, ExpeditionDetailData> = {
  2: {
    expeditionId: 2,
    expeditionNumber: "194112",
    assignedTo: "Alba Panato",
    currentStatusLabel: "Abierta - en transito",
    currentStatusDate: "06/11/2025 11:33",
    originType: "Almacen",
    originCode: "AL1",
    originInfoTitle: "AL1 ALMACEN DE ALICANTE (Alicante)",
    originInfoDescription: "ALMACEN@NECOMPLUS.COM",
    destinationType: "Almacen",
    destinationCode: "AL95",
    destinationInfoTitle: "AL95 Almacen de Cantabria (Datinsa Norte)",
    destinationInfoDescription: "Cantabria (TB51) · almacen@datinsa.com",
    sentAt: "2025-11-06T11:33",
    expectedReceptionAt: "",
    packages: "1",
    kilos: "10",
    observations: "",
    terminalSource: "ns",
    terminalSearchValue: "",
    terminalSummary: terminalSummaryMock,
    terminalDetails: terminalDetailsMock,
  },
  5: {
    expeditionId: 5,
    expeditionNumber: "194188",
    assignedTo: "Lucia Torres",
    currentStatusLabel: "Abierta",
    currentStatusDate: "06/11/2025 09:10",
    originType: "Almacen",
    originCode: "AL1",
    originInfoTitle: "AL1 ALMACEN DE ALICANTE (Alicante)",
    originInfoDescription: "ALMACEN@NECOMPLUS.COM",
    destinationType: "Almacen",
    destinationCode: "AL48",
    destinationInfoTitle: "AL48 Lectus (Barcelona)",
    destinationInfoDescription: "lectus2012sl@gmail.com · a.amezcua.rodriguez@gmail.com",
    sentAt: "2025-11-06T09:10",
    expectedReceptionAt: "2025-11-07T17:00",
    packages: "3",
    kilos: "24",
    observations: "Prioridad media. Revisar accesorios al preparar los bultos.",
    terminalSource: "csv",
    terminalSearchValue: "",
    terminalSummary: terminalSummaryMock,
    terminalDetails: terminalDetailsMock,
  },
};

export function createNewExpeditionDraft(): ExpeditionDetailData {
  return {
    expeditionNumber: "Nueva",
    assignedTo: "Usuario actual",
    currentStatusLabel: "Borrador",
    currentStatusDate: "Pendiente de guardar",
    originType: "Almacen",
    originCode: "AL1",
    originInfoTitle: "AL1 ALMACEN DE ALICANTE (Alicante)",
    originInfoDescription: "ALMACEN@NECOMPLUS.COM",
    destinationType: "Almacen",
    destinationCode: "AL95",
    destinationInfoTitle: "AL95 Almacen de Cantabria (Datinsa Norte)",
    destinationInfoDescription: "Cantabria (TB51) · almacen@datinsa.com",
    sentAt: "2026-04-06T09:30",
    expectedReceptionAt: "",
    packages: "",
    kilos: "",
    observations: "",
    terminalSource: "ns",
    terminalSearchValue: "",
    terminalSummary: terminalSummaryMock,
    terminalDetails: terminalDetailsMock,
  };
}
