import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import SNSearchDeleteConfirmModal from "../components/SNSearch/SNSearchDeleteConfirmModal";
import Aisle from "../components/stockUbication/Aisle";
import AddPalletButton from "../components/stockUbication/AddPalletButton";
import AddBoxButton from "../components/stockUbication/AddBoxButton";
import FormBox, { type FormBoxMode, type NuevaCajaPayload } from "../components/stockUbication/forms/FormBox";
import FormPallet from "../components/stockUbication/forms/FormPallet";
import { assignBoxToPallet, createBox, getBoxCapacity, type BoxCapacityResponse, type FreeBox } from "../services/boxService";
import {
  createPallet,
  deletePallet,
  getFreePallets,
  getPalletById,
  movePalletToUbicacion,
  updatePalletDescription,
  unassignBoxFromPallet,
  type FreePalletResponse,
  type PalletDetailResponse,
} from "../services/palletService";
import { getWarehouseMap } from "../services/warehouseMapService";
import { ApiHttpError } from "../services/apiClient";
import type { WarehouseMapItem } from "../types/warehouseMap.types";
import { getCajaById } from "../services/cajaTerminalService";
import "../styles/StockUbicationPage.scss";

const resolvePalletBrand = (value?: string | null): string | null => {
  const raw = (value ?? "").trim();
  if (!raw) return null;
  if (raw.includes("-")) {
    const parts = raw.split("-").map((p) => p.trim()).filter(Boolean);
    if (parts.length >= 2) return parts[1];
  }
  return raw;
};

const isAutoGeneratedPalletDescription = (value?: string | null): boolean => {
  const text = (value ?? "").trim();
  if (!text) return true;
  return /^Pasillo\s+\d+\s+-\s+Estanter[ií]a\s+.+\s+-\s+Nivel\s+\d+$/i.test(text);
};

export default function StockUbicationPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const { ubicacionId } = useParams<{ ubicacionId?: string }>();
  const [detalles, setDetalles] = useState<WarehouseMapItem[]>([]);
  const [isLoadingMap, setIsLoadingMap] = useState(false);
  const [mapError, setMapError] = useState("");
  const [huecoSeleccionado, setHuecoSeleccionado] = useState<WarehouseMapItem | null>();
  const [mostrarFormCaja, setMostrarFormCaja] = useState(false);
  const [huecoActivo, setHuecoActivo] = useState<WarehouseMapItem | null>(null);
  const [mostrarFormPallet, setMostrarFormPallet] = useState(false);
  const [palletActionMode, setPalletActionMode] = useState<"new" | "existing" | null>(null);
  const [formBoxMode, setFormBoxMode] = useState<FormBoxMode | null>(null);
  const [boxCapacities, setBoxCapacities] = useState<Record<number, BoxCapacityResponse | "loading" | "error">>({});
  const [boxModelsById, setBoxModelsById] = useState<Record<number, string>>({});
  const [actionMessage, setActionMessage] = useState<{ type: "success" | "warning" | "error"; text: string } | null>(null);
  const [isUnassigningBoxId, setIsUnassigningBoxId] = useState<number | null>(null);
  const [isUnassigningPallet, setIsUnassigningPallet] = useState(false);
  const [selectedPalletDetail, setSelectedPalletDetail] = useState<PalletDetailResponse | null>(null);
  const [selectedPalletBrand, setSelectedPalletBrand] = useState<string | null>(null);
  const [freePallets, setFreePallets] = useState<FreePalletResponse[]>([]);
  const [selectedFreePalletId, setSelectedFreePalletId] = useState<number | null>(null);
  const [isLoadingFreePallets, setIsLoadingFreePallets] = useState(false);
  const [isMovingPallet, setIsMovingPallet] = useState(false);
  const [confirmAction, setConfirmAction] = useState<
    | { type: "box"; paletId: number; cajaId: number }
    | { type: "unassignPallet"; paletId: number }
    | { type: "deletePallet"; paletId: number }
    | null
  >(null);

  const abrirFormCaja = (hueco: WarehouseMapItem) => {
    setHuecoActivo(hueco);
    setFormBoxMode(null);
    setMostrarFormCaja(true);
  };

  const cerrarFormCaja = () => {
    setMostrarFormCaja(false);
    setFormBoxMode(null);
  };

  const abrirFormPallet = (hueco: WarehouseMapItem) => {
    setHuecoActivo(hueco);
    setPalletActionMode(null);
    setSelectedFreePalletId(null);
    setFreePallets([]);
    setMostrarFormPallet(true);
  };

  const cerrarFormPallet = () => {
    setMostrarFormPallet(false);
    setPalletActionMode(null);
    setSelectedFreePalletId(null);
  };

  const movePaletIdFromQuery = useMemo(() => {
    const query = new URLSearchParams(location.search);
    const value = query.get("movePaletId");
    if (!value) return null;
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }, [location.search]);

  const loadMap = async (options?: { keepError?: boolean }): Promise<WarehouseMapItem[]> => {
    try {
      setIsLoadingMap(true);
      if (!options?.keepError) {
        setMapError("");
      }
      const items = await getWarehouseMap();
      setDetalles(items);
      return items;
    } catch (error) {
      const message =
        error instanceof ApiHttpError
          ? error.message
          : error instanceof Error
            ? error.message
            : "No se pudo cargar el mapa de almacén.";
      setMapError(message);
      throw error;
    } finally {
      setIsLoadingMap(false);
    }
  };

  useEffect(() => {
    void loadMap();
  }, []);

  const pasillosMap = new Map<number, WarehouseMapItem[]>();
  const hasBoxesInSelectedPallet = (huecoSeleccionado?.cajas.length ?? 0) > 0;

  const getActionAlertClass = (type: "success" | "warning" | "error") => {
    if (type === "success") return "alert-success";
    if (type === "warning") return "alert-warning";
    return "alert-danger";
  };

  const getCapacityLabel = (cajaId: number) => {
    const capacity = boxCapacities[cajaId];
    if (typeof capacity === "undefined" || capacity === "loading") return "--/--";
    if (capacity === "error") return "N/A";
    return `${capacity.terminalesActuales}/${capacity.capacidadMaxima}`;
  };

  const isCapacityOverflow = (cajaId: number) => {
    const capacity = boxCapacities[cajaId];
    return typeof capacity === "object" && capacity !== null && capacity.terminalesActuales > capacity.capacidadMaxima;
  };

  detalles.forEach((datoAlmacen) => {
    const pasilloId = datoAlmacen.pasillo.id;

    if (!pasillosMap.has(pasilloId)) {
      pasillosMap.set(pasilloId, []);
    }

    pasillosMap.get(pasilloId)?.push(datoAlmacen);
  });

  const handleHuecoClick = (ubicacion: WarehouseMapItem) => {
    if (movePaletIdFromQuery !== null) {
      const ubicacionAlmacenId = ubicacion.ubicacionAlmacenId;
      if (ubicacionAlmacenId === null || typeof ubicacionAlmacenId === "undefined") {
        setActionMessage({ type: "error", text: "El hueco seleccionado no tiene ubicacionAlmacenId válido." });
        return;
      }

      void (async () => {
        setActionMessage(null);
        setIsMovingPallet(true);
        try {
          await movePalletToUbicacion(movePaletIdFromQuery, { ubicacionAlmacenId });
          const destinationRef =
            typeof ubicacion.pasillo?.numero === "number" &&
            ubicacion.estanteria?.descripcion &&
            typeof ubicacion.estanteria?.nivel === "number"
              ? `Pasillo ${ubicacion.pasillo.numero} - Estantería ${ubicacion.estanteria.descripcion} - Nivel ${ubicacion.estanteria.nivel}`
              : (ubicacion.referencia ?? "").trim() || `idHueco ${ubicacion.idHueco}`;
          const currentDescription = selectedPalletDetail?.descripcion ?? huecoSeleccionado?.pale?.descripcion ?? null;
          const shouldAutoUpdateDescription = isAutoGeneratedPalletDescription(currentDescription);
          let descriptionUpdated = true;
          if (shouldAutoUpdateDescription) {
            try {
              await updatePalletDescription(movePaletIdFromQuery, { descripcion: destinationRef });
            } catch {
              descriptionUpdated = false;
            }
          }

          await loadMap({ keepError: true });
          navigate("/stock", { replace: true });
          setActionMessage(
            shouldAutoUpdateDescription && descriptionUpdated
              ? {
                  type: "success",
                  text: `Palé ${movePaletIdFromQuery} movido y descripción actualizada (${destinationRef}).`,
                }
              : shouldAutoUpdateDescription
                ? {
                    type: "warning",
                    text: "Palé movido, pero no se pudo actualizar la descripción.",
                  }
                : {
                    type: "success",
                    text: `Palé ${movePaletIdFromQuery} movido correctamente.`,
                  }
          );
        } catch (error) {
          const message = error instanceof ApiHttpError ? error.message : "No se pudo mover el palé.";
          setActionMessage({ type: "error", text: message });
        } finally {
          setIsMovingPallet(false);
        }
      })();
      return;
    }

    console.log("Habitáculo seleccionado:", {
      idHueco: ubicacion.idHueco,
      pasillo: ubicacion.pasillo.numero,
      nivel: ubicacion.estanteria.nivel,
    });
    setActionMessage(null);
    navigate(`/stock/ubicacion/${ubicacion.idHueco}`);
  };

  const handleStartMovePallet = (paletId: number) => {
    setHuecoSeleccionado(null);
    setActionMessage(null);
    navigate(`/stock?movePaletId=${paletId}`);
  };

  const handleAssignExistingPallet = async () => {
    if (!huecoActivo?.ubicacionAlmacenId || !selectedFreePalletId) {
      throw new Error("Selecciona un palé y una ubicación válida.");
    }
    await movePalletToUbicacion(selectedFreePalletId, { ubicacionAlmacenId: huecoActivo.ubicacionAlmacenId });
    const items = await loadMap({ keepError: true });
    refreshSelectedHueco(items);
    setMostrarFormPallet(false);
    setPalletActionMode(null);
    setSelectedFreePalletId(null);
    setActionMessage({ type: "success", text: "Palé asignado correctamente al hueco." });
  };

  const handleCreateBox = async (payload: NuevaCajaPayload) => {
    await createBox(payload);
    setMostrarFormCaja(false);
    setFormBoxMode(null);
    const items = await loadMap({ keepError: true });
    refreshSelectedHueco(items);
    setActionMessage({
      type: "success",
      text: `Caja ${payload.etiqueta} creada correctamente. Ahora asígnala al palé desde "Asignar una caja al palé".`,
    });
  };

  const handleAssignExistingBox = async (box: FreeBox) => {
    const paletId = huecoActivo?.pale?.id ?? null;
    if (!paletId) {
      throw new Error("No hay palé seleccionado para asignar la caja.");
    }
    await assignBoxToPallet(box.id, paletId);
    setMostrarFormCaja(false);
    setFormBoxMode(null);
    await loadMap({ keepError: true });

    navigate(`/stock/boxes/${box.id}/terminals`, {
      state: {
        huecoId: huecoActivo?.idHueco,
        ubicacion: `${huecoActivo?.referencia ?? ""} · Pasillo ${huecoActivo?.pasillo.numero ?? "-"} · Estantería ${huecoActivo?.estanteria.descripcion ?? "-"}${typeof huecoActivo?.estanteria.nivel === "number" ? `/${huecoActivo.estanteria.nivel}` : ""}`,
        etiqueta: box.etiqueta,
        marca: box.modeloProducto?.split(" ")[0] ?? "",
        modelo: box.modeloProducto?.split(" ").slice(1).join(" ") ?? "",
        capacidadTotal: box.maxCapacity ?? 0,
        unidades: 0,
      },
    });
  };

  const handleOpenBoxTerminals = (caja: WarehouseMapItem["cajas"][number]) => {
    const terminals = (caja.terminales ?? []).map((terminal) => ({
      sn: terminal.numeroSerie?.toUpperCase?.() ?? "",
      isValid: true,
      reason: undefined,
      scannedAt: "Precargado",
    })).filter((item) => Boolean(item.sn));

    navigate(`/stock/boxes/${caja.id}/terminals`, {
      state: {
        huecoId: huecoSeleccionado?.idHueco,
        ubicacion: `${huecoSeleccionado?.referencia ?? ""} · Pasillo ${huecoSeleccionado?.pasillo.numero ?? "-"} · Estantería ${huecoSeleccionado?.estanteria.descripcion ?? "-"}${typeof huecoSeleccionado?.estanteria.nivel === "number" ? `/${huecoSeleccionado.estanteria.nivel}` : ""}`,
        etiqueta: caja.etiqueta,
        marca: caja.terminales?.[0]?.marca ?? "",
        modelo: caja.modeloProducto ?? caja.terminales?.[0]?.modelo ?? "",
        capacidadTotal: caja.maxCapacity ?? huecoSeleccionado?.estanteria.capacidadMaxCajas ?? 0,
        unidades: terminals.length,
        initialRows: terminals,
      },
    });
  };

  const refreshSelectedHueco = (items: WarehouseMapItem[]) => {
    const selectedId = huecoSeleccionado?.idHueco ?? huecoActivo?.idHueco ?? null;
    if (!selectedId) return;

    const updated = items.find((item) => item.idHueco === selectedId) ?? null;
    if (updated) {
      setHuecoSeleccionado(updated);
      setHuecoActivo(updated);
    }
  };

  const refreshMapAndSelectedHueco = async (): Promise<WarehouseMapItem | null> => {
    const items = await getWarehouseMap();
    setDetalles(items);
    const selectedId = huecoSeleccionado?.idHueco ?? huecoActivo?.idHueco ?? null;
    const updated = selectedId ? items.find((item) => item.idHueco === selectedId) ?? null : null;
    refreshSelectedHueco(items);
    return updated;
  };

  const handleUnassignBox = async (paletId: number, cajaId: number) => {
    setActionMessage(null);
    setIsUnassigningBoxId(cajaId);
    try {
      const response = await unassignBoxFromPallet(paletId, cajaId);
      setActionMessage({ type: "success", text: response.mensaje || "Caja desasignada del palé con éxito." });
      await refreshMapAndSelectedHueco();
    } catch (error) {
      const message = error instanceof ApiHttpError ? error.message : "No se pudo desasignar la caja.";
      setActionMessage({ type: "error", text: message });
    } finally {
      setIsUnassigningBoxId(null);
    }
  };

  const handleUnassignPallet = async (paletId: number) => {
    setActionMessage(null);
    setIsUnassigningPallet(true);
    try {
      const response = await movePalletToUbicacion(paletId, { ubicacionAlmacenId: null });
      setActionMessage({ type: "success", text: response.mensaje || "Palé desasignado de la ubicación con éxito." });
      await refreshMapAndSelectedHueco();
    } catch (error) {
      const message = error instanceof ApiHttpError ? error.message : "No se pudo desasignar el palé de la ubicación.";
      setActionMessage({ type: "error", text: message });
    } finally {
      setIsUnassigningPallet(false);
    }
  };

  const handleDeletePallet = async (paletId: number) => {
    setActionMessage(null);
    setIsUnassigningPallet(true);
    try {
      const response = await deletePallet(paletId);
      setActionMessage({ type: "success", text: response.mensaje || "Palé eliminado con éxito." });
      await refreshMapAndSelectedHueco();
    } catch (error) {
      const message = error instanceof ApiHttpError ? error.message : "No se pudo eliminar el palé.";
      setActionMessage({ type: "error", text: message });
    } finally {
      setIsUnassigningPallet(false);
    }
  };

  useEffect(() => {
    const cajas = huecoSeleccionado?.cajas ?? [];
    if (cajas.length === 0) {
      return;
    }

    let cancelled = false;

    const loadCapacities = async () => {
      const entries = await Promise.all(
        cajas.map(async (caja) => {
          try {
            const capacity = await getBoxCapacity(caja.id);
            return [caja.id, capacity] as const;
          } catch (error) {
            console.warn(`No se pudo cargar capacidad para caja ${caja.id}`, error);
            return [caja.id, "error"] as const;
          }
        })
      );

      if (cancelled) return;

      setBoxCapacities((prev) => {
        const next = { ...prev };
        for (const [id, capacity] of entries) {
          next[id] = capacity;
        }
        return next;
      });
    };

    for (const caja of cajas) {
      setBoxCapacities((prev) => (typeof prev[caja.id] === "undefined" ? { ...prev, [caja.id]: "loading" } : prev));
    }

    void loadCapacities();

    return () => {
      cancelled = true;
    };
  }, [huecoSeleccionado]);

  useEffect(() => {
    const cajas = huecoSeleccionado?.cajas ?? [];
    if (cajas.length === 0) return;

    const missing = cajas
      .filter((caja) => {
        const modelFromMap = (caja.modeloProducto ?? "").trim();
        const modelFromTerminal = caja.terminales?.[0]?.modelo?.trim() ?? "";
        return !modelFromMap && !modelFromTerminal && !boxModelsById[caja.id];
      })
      .map((caja) => caja.id);

    if (missing.length === 0) return;

    let cancelled = false;
    const loadMissingModels = async () => {
      const entries = await Promise.all(
        missing.map(async (id) => {
          try {
            const caja = await getCajaById(id);
            return [id, (caja.modeloProducto ?? "").trim()] as const;
          } catch {
            return [id, ""] as const;
          }
        })
      );

      if (cancelled) return;

      setBoxModelsById((prev) => {
        const next = { ...prev };
        for (const [id, modelo] of entries) {
          if (modelo) next[id] = modelo;
        }
        return next;
      });
    };

    void loadMissingModels();

    return () => {
      cancelled = true;
    };
  }, [boxModelsById, huecoSeleccionado]);

  useEffect(() => {
    if (!actionMessage) return;
    const timeout = window.setTimeout(() => setActionMessage(null), 2000);
    return () => window.clearTimeout(timeout);
  }, [actionMessage]);

  useEffect(() => {
    const navState = (location.state as { actionFeedback?: string } | null) ?? null;
    if (navState?.actionFeedback) {
      setActionMessage({ type: "success", text: navState.actionFeedback });
      navigate(location.pathname, { replace: true, state: null });
    }
  }, [location.pathname, location.state, navigate]);

  useEffect(() => {
    if (!ubicacionId || detalles.length === 0) return;
    const id = Number(ubicacionId);
    if (!Number.isFinite(id)) return;
    const selected = detalles.find((item) => item.idHueco === id) ?? null;
    setHuecoSeleccionado(selected ?? null);
    if (selected) {
      setHuecoActivo(selected);
    }
  }, [ubicacionId, detalles]);

  useEffect(() => {
    const paletId = huecoSeleccionado?.pale?.id;
    if (!paletId) {
      setSelectedPalletDetail(null);
      setSelectedPalletBrand(null);
      return;
    }

    let cancelled = false;

    const loadPalletDetail = async () => {
      try {
        const detail = await getPalletById(paletId);
        if (!cancelled) {
          setSelectedPalletDetail(detail);
          const brandFromPallet = resolvePalletBrand(detail.codigoMarca) ?? resolvePalletBrand(huecoSeleccionado?.pale?.codigoMarca) ?? null;
          setSelectedPalletBrand(brandFromPallet);
        }
      } catch {
        if (!cancelled) {
          setSelectedPalletDetail(null);
          setSelectedPalletBrand(resolvePalletBrand(huecoSeleccionado?.pale?.codigoMarca) ?? null);
        }
      }
    };

    void loadPalletDetail();

    return () => {
      cancelled = true;
    };
  }, [huecoSeleccionado?.pale?.id]);

  useEffect(() => {
    if (!mostrarFormPallet || palletActionMode !== "existing") return;

    let cancelled = false;
    const loadFreePallets = async () => {
      try {
        setIsLoadingFreePallets(true);
        const items = await getFreePallets();
        if (!cancelled) setFreePallets(items);
      } catch (error) {
        if (!cancelled) {
          const message = error instanceof ApiHttpError ? error.message : "No se pudieron cargar los palés libres.";
          setActionMessage({ type: "error", text: message });
        }
      } finally {
        if (!cancelled) setIsLoadingFreePallets(false);
      }
    };

    void loadFreePallets();
    return () => {
      cancelled = true;
    };
  }, [mostrarFormPallet, palletActionMode]);

  const closeSlotDetailModal = () => {
    setHuecoSeleccionado(null);
    setActionMessage(null);
    navigate("/stock");
  };

  return (
    <div className="container py-4">
      {huecoSeleccionado && (
        <>
          <div className="modal-backdrop fade show stock-overlay-backdrop" onClick={closeSlotDetailModal} />
          <div className="modal fade show d-block stock-overlay-modal" role="dialog" aria-modal="true">
            <div className="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg">
              <div className="modal-content stock-slot-modal">
              <div className="modal-header">
                <div className="stock-slot-modal__header-main">
                  <div>
                    <p className="stock-slot-modal__eyebrow mb-1">Detalle de ubicación</p>
                    <h5 className="modal-title stock-slot-modal__title">{huecoSeleccionado.referencia}</h5>
                  </div>
                  <div className="stock-slot-modal__header-metrics">
                    <article className="stock-slot-metric-card--compact">
                      <span className="stock-slot-metric-card__icon" aria-hidden="true">
                        <i className="bi bi-layout-sidebar-inset" />
                      </span>
                      <p className="stock-slot-metric-card__label">Pasillo</p>
                      <p className="stock-slot-metric-card__value">{huecoSeleccionado.pasillo.numero}</p>
                    </article>
                    <article className="stock-slot-metric-card--compact">
                      <span className="stock-slot-metric-card__icon" aria-hidden="true">
                        <i className="bi bi-layers" />
                      </span>
                      <p className="stock-slot-metric-card__label">Nivel estantería</p>
                      <p className="stock-slot-metric-card__value">{huecoSeleccionado.estanteria.nivel}</p>
                    </article>
                  </div>
                </div>
                <button
                  className="btn-close"
                  onClick={closeSlotDetailModal}
                />
              </div>

              <div className="modal-body stock-slot-modal__body">
                {actionMessage && (
                  <div className={`alert py-2 ${getActionAlertClass(actionMessage.type)}`}>
                    {actionMessage.text}
                  </div>
                )}
                <div className="stock-slot-modal__layout">
                  <section className="stock-slot-modal__left">
                    <article className="stock-slot-pallet-card">
                      <div className="d-flex justify-content-between align-items-center mb-3">
                        <h6 className="stock-slot-pallet-card__title mb-0">Información del palé</h6>
                        <span className={`stock-slot-pallet-card__badge ${huecoSeleccionado.pale ? "is-active" : "is-empty"}`}>
                          {huecoSeleccionado.pale ? "Activo" : "Vacío"}
                        </span>
                      </div>

                      {huecoSeleccionado.pale ? (
                        <div className="stock-slot-pallet-card__grid">
                          <div className="stock-slot-pallet-card__field stock-slot-pallet-info-card stock-slot-pallet-card__field--full">
                            <p className="stock-slot-pallet-card__label">Marca permitida</p>
                            <p className="stock-slot-pallet-card__value">
                              <span className="stock-slot-pallet-card__value-icon" aria-hidden="true">
                                <i className="bi bi-tag" />
                              </span>
                              {selectedPalletDetail?.codigoMarca || huecoSeleccionado.pale.codigoMarca || "No definida"}
                            </p>
                          </div>
                          <div className="stock-slot-pallet-card__field stock-slot-pallet-info-card">
                            <p className="stock-slot-pallet-card__label">Material</p>
                            <p className="stock-slot-pallet-card__value">
                             
                              {huecoSeleccionado.pale.material}
                            </p>
                          </div>
                          <div className="stock-slot-pallet-card__field stock-slot-pallet-info-card">
                            <p className="stock-slot-pallet-card__label">Tipo</p>
                            <p className="stock-slot-pallet-card__value">
                             
                              {huecoSeleccionado.pale.tipo}
                            </p>
                          </div>
                          <div className="stock-slot-pallet-card__field stock-slot-pallet-card__field--full stock-slot-pallet-info-card">
                            <p className="stock-slot-pallet-card__label">Descripción</p>
                            <p className="stock-slot-pallet-card__value">
                              <span className="stock-slot-pallet-card__value-icon" aria-hidden="true">
                                <i className="bi bi-card-text" />
                              </span>
                              {selectedPalletDetail?.descripcion || huecoSeleccionado.pale.descripcion}
                            </p>
                          </div>
                          <div className="stock-slot-pallet-card__field stock-slot-pallet-card__field--full d-flex flex-wrap gap-2">
                            <button
                              type="button"
                              className="btn btn-outline-info btn-sm d-inline-flex align-items-center gap-1"
                              onClick={() => {
                                if (huecoSeleccionado.pale?.id) {
                                  handleStartMovePallet(huecoSeleccionado.pale.id);
                                }
                              }}
                              disabled={isMovingPallet}
                            >
                              <i className="bi bi-arrow-left-right" aria-hidden="true" />
                              Mover palé
                            </button>
                            <button
                              type="button"
                              className="btn btn-outline-secondary btn-sm d-inline-flex align-items-center gap-1"
                              onClick={() => {
                                if (huecoSeleccionado.pale?.id) {
                                  setConfirmAction({
                                    type: "unassignPallet",
                                    paletId: huecoSeleccionado.pale.id,
                                  });
                                }
                              }}
                              disabled={isUnassigningPallet}
                            >
                              <i className="bi bi-x-circle" aria-hidden="true" />
                              {isUnassigningPallet ? "Quitando..." : "Bajar palé"}
                            </button>
                            <button
                              type="button"
                              className="btn btn-outline-danger btn-sm d-inline-flex align-items-center gap-1"
                              onClick={() => {
                                if (huecoSeleccionado.pale?.id) {
                                  setConfirmAction({
                                    type: "deletePallet",
                                    paletId: huecoSeleccionado.pale.id,
                                  });
                                }
                              }}
                              disabled={isUnassigningPallet || hasBoxesInSelectedPallet}
                              title={hasBoxesInSelectedPallet ? "Solo puedes borrar el palé cuando no tenga cajas." : undefined}
                            >
                              <i className="bi bi-trash3" aria-hidden="true" />
                              Borrar palé
                            </button>
                          </div>
                        </div>
                      ) : (
                        <div className="stock-slot-pallet-card__empty">
                          <p className="mb-3 text-muted">No hay palé asignado todavía.</p>
                          <AddPalletButton onClick={() => abrirFormPallet(huecoSeleccionado)} />
                        </div>
                      )}
                    </article>
                  </section>

                  <aside className="stock-slot-modal__right">
                    <article className="stock-slot-capacity-card">
                      <p className="stock-slot-capacity-card__label">Capacidad utilizada</p>
                      <div
                        className="stock-slot-capacity-card__ring"
                        style={{
                          background: `conic-gradient(#0c677f ${(huecoSeleccionado.ocupacionActual / Math.max(huecoSeleccionado.estanteria.capacidadMaxCajas, 1)) * 360}deg, #d4dde2 0deg)`,
                        }}
                      >
                        <div className="stock-slot-capacity-card__ring-inner">
                          <p className="stock-slot-capacity-card__count mb-0">
                            {huecoSeleccionado.ocupacionActual}/{huecoSeleccionado.estanteria.capacidadMaxCajas}
                          </p>
                          <p className="stock-slot-capacity-card__sub mb-0" aria-label="Cajas">
                            <i className="bi bi-box-seam" />
                          </p>
                        </div>
                      </div>

                      {huecoSeleccionado.cajas.length > 0 ? (
                        <div className="stock-slot-box-list">
                          {huecoSeleccionado.cajas.map((caja) => (
                            <div className="stock-slot-box-list__item stock-slot-box-list__item--row" key={caja.id}>
                              <button
                                type="button"
                                className="stock-slot-box-list__item stock-slot-box-list__item--button"
                                onClick={() => handleOpenBoxTerminals(caja)}
                              >
                                <span className="stock-slot-box-list__main">
                                  <span>{caja.etiqueta}</span>
                                  <span className="stock-slot-box-list__model">
                                    {caja.modeloProducto ||
                                      (caja.terminales?.[0]
                                        ? `${caja.terminales[0].marca ?? ""} ${caja.terminales[0].modelo ?? ""}`.trim()
                                        : "") ||
                                      boxModelsById[caja.id] ||
                                      "Modelo no definido"}
                                  </span>
                                </span>
                                <span
                                  className={`stock-slot-box-list__capacity ${isCapacityOverflow(caja.id) ? "is-overflow" : ""}`}
                                >
                                  <i className="bi bi-upc-scan" aria-hidden="true" />
                                  {getCapacityLabel(caja.id)}
                                </span>
                              </button>
                              <span className="stock-slot-box-list__actions">
                                <button
                                  type="button"
                                  className="btn btn-link text-danger p-0 d-inline-flex align-items-center gap-1"
                                  onClick={() => {
                                    if (huecoSeleccionado.pale?.id) {
                                      setConfirmAction({ type: "box", paletId: huecoSeleccionado.pale.id, cajaId: caja.id });
                                    }
                                  }}
                                  disabled={isUnassigningBoxId === caja.id}
                                >
                                  <i className="bi bi-x-circle" aria-hidden="true" />
                                </button>
                              </span>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <div className="stock-slot-box-list__empty">Sin cajas</div>
                      )}
                    </article>
                  </aside>
                </div>

                {huecoSeleccionado.cajas.length < huecoSeleccionado.estanteria.capacidadMaxCajas && huecoSeleccionado.pale !== null ? (
                  <div className="stock-slot-modal__cta">
                    <AddBoxButton onClick={() => abrirFormCaja(huecoSeleccionado)} />
                  </div>
                ) : null}
              </div>
              </div>
            </div>
          </div>
        </>
      )}

      {mostrarFormCaja && huecoActivo && (
        <>
          <div className="modal-backdrop fade show stock-nested-modal-backdrop" />
          <div className="modal fade show d-block stock-nested-modal">
            <div className="modal-dialog modal-dialog-centered">
              <div className={`modal-content p-3 ${formBoxMode === "registered" ? "stock-box-modal-content--registered" : ""}`.trim()}>
              {!formBoxMode && (
                <div className="box-mode-selector">
                  <div className="d-flex justify-content-between align-items-start mb-2">
                    <h5 className="mb-0 stock-modal-eyebrow-title">¿Que desea hacer?</h5>
                    <button type="button" className="btn-close" aria-label="Cerrar" onClick={cerrarFormCaja} />
                  </div>
                  <div className="box-mode-selector__grid">
                    <button type="button" className="box-mode-card" onClick={() => setFormBoxMode("manual")}>
                      <span className="box-mode-card__icon" aria-hidden="true">
                        <i className="bi bi-plus-square" />
                      </span>
                      <span className="box-mode-card__title">Dar de alta una caja</span>
                      <span className="box-mode-card__desc">Crear una caja nueva para este palé.</span>
                    </button>

                    <button type="button" className="box-mode-card" onClick={() => setFormBoxMode("registered")}>
                      <span className="box-mode-card__icon" aria-hidden="true">
                        <i className="bi bi-archive" />
                      </span>
                      <span className="box-mode-card__title">Asignar una caja al palé</span>
                      <span className="box-mode-card__desc">Usar una caja ya registrada en el sistema.</span>
                    </button>
                  </div>
                </div>
              )}

              {formBoxMode && (
                <>
                  <div className="d-flex justify-content-between align-items-start mb-2">
                    <h5 className="mb-0 stock-modal-eyebrow-title">{formBoxMode === "manual" ? "Dar de alta una caja" : "Caja registrada"}</h5>
                    <button type="button" className="btn-close" aria-label="Cerrar" onClick={cerrarFormCaja} />
                  </div>
                  <FormBox
                    hueco={huecoActivo}
                    mode={formBoxMode}
                    allowedBrand={selectedPalletBrand}
                    onSubmitNew={handleCreateBox}
                    onSubmitExisting={handleAssignExistingBox}
                    onCancel={cerrarFormCaja}
                  />
                </>
              )}
              </div>
            </div>
          </div>
        </>
      )}

      {mostrarFormPallet && huecoActivo && (
        <>
          <div className="modal-backdrop fade show stock-nested-modal-backdrop" />
          <div className="modal fade show d-block stock-nested-modal">
            <div className="modal-dialog modal-dialog-centered">
              <div className="modal-content p-3">
                {!palletActionMode && (
                  <div className="box-mode-selector">
                    <div className="d-flex justify-content-between align-items-start mb-2">
                      <h5 className="mb-0 stock-modal-eyebrow-title">¿Que desea hacer?</h5>
                      <button type="button" className="btn-close" aria-label="Cerrar" onClick={cerrarFormPallet} />
                    </div>
                    <div className="box-mode-selector__grid">
                      <button type="button" className="box-mode-card" onClick={() => setPalletActionMode("new")}>
                        <span className="box-mode-card__icon" aria-hidden="true">
                          <i className="bi bi-plus-square" />
                        </span>
                        <span className="box-mode-card__title">Crear palé nuevo</span>
                        <span className="box-mode-card__desc">Dar de alta un palé y asignarlo a este hueco.</span>
                      </button>

                      <button type="button" className="box-mode-card" onClick={() => setPalletActionMode("existing")}>
                        <span className="box-mode-card__icon" aria-hidden="true">
                          <i className="bi bi-grid-3x3-gap" />
                        </span>
                        <span className="box-mode-card__title">Asignar palé existente</span>
                        <span className="box-mode-card__desc">Seleccionar un palé libre ya creado.</span>
                      </button>
                    </div>
                  </div>
                )}

                {palletActionMode === "new" && (
                  <>
                    <div className="d-flex justify-content-between align-items-start mb-2">
                      <h5 className="mb-0 stock-modal-eyebrow-title">Añadir palé al hueco</h5>
                      <button type="button" className="btn-close" aria-label="Cerrar" onClick={cerrarFormPallet} />
                    </div>
                    <FormPallet
                      idHueco={huecoActivo.idHueco}
                      onSubmit={async (data) => {
                        if (huecoActivo.ubicacionAlmacenId === null || typeof huecoActivo.ubicacionAlmacenId === "undefined") {
                          throw new Error("La ubicación seleccionada no tiene ID real de almacén");
                        }

                        const manualDescription = data.descripcion.trim();
                        const descripcion =
                          manualDescription ||
                          `Pasillo ${huecoActivo.pasillo.numero} - Estantería ${huecoActivo.estanteria.descripcion} - Nivel ${huecoActivo.estanteria.nivel}`;
                        const codigoMarca = data.marca.trim();
                        const payload = {
                          descripcion,
                          material: data.material,
                          tipo: data.tipo,
                          capacidadMaxCajas: data.capacidadMaxCajas,
                          codigoMarca,
                          ubicacionAlmacenId: huecoActivo.ubicacionAlmacenId,
                          cajas: [] as [],
                        };

                        console.log("Create pallet request ids:", {
                          idHueco: huecoActivo.idHueco,
                          ubicacionAlmacenId: huecoActivo.ubicacionAlmacenId,
                        });
                        console.log("Create pallet payload:", payload);

                        await createPallet(payload);
                        const items = await getWarehouseMap();
                        setDetalles(items);
                        refreshSelectedHueco(items);
                        setMostrarFormPallet(false);
                        setPalletActionMode(null);
                      }}
                      onCancel={cerrarFormPallet}
                      canSubmit={typeof huecoActivo.ubicacionAlmacenId === "number"}
                      blockedMessage="La ubicación seleccionada no tiene ID real de almacén"
                    />
                  </>
                )}

                {palletActionMode === "existing" && (
                  <>
                    <div className="d-flex justify-content-between align-items-start mb-2">
                      <h5 className="mb-0 stock-modal-eyebrow-title">Asignar palé existente</h5>
                      <button type="button" className="btn-close" aria-label="Cerrar" onClick={cerrarFormPallet} />
                    </div>
                    <div className="stock-box-form stock-box-form--registered">
                      <div className="mb-3 stock-box-form__group">
                        <label className="form-label">Palé libre</label>
                        <select
                          className="form-select"
                          value={selectedFreePalletId ?? ""}
                          onChange={(event) => setSelectedFreePalletId(event.target.value ? Number(event.target.value) : null)}
                          disabled={isLoadingFreePallets}
                        >
                          <option value="">{isLoadingFreePallets ? "Cargando palés..." : "Selecciona un palé libre"}</option>
                          {freePallets.map((pallet) => (
                            <option key={pallet.id} value={pallet.id}>
                              {`Palé #${pallet.id} - ${pallet.codigoMarca ?? "Sin marca"} - ${pallet.material}/${pallet.tipo} - Cap. ${pallet.capacidadMaxCajas}`}
                            </option>
                          ))}
                        </select>
                      </div>

                      <div className="d-flex gap-2 justify-content-end">
                        <button
                          type="button"
                          className="btn stock-box-form__btn stock-box-form__btn--save"
                          disabled={selectedFreePalletId === null || isLoadingFreePallets}
                          onClick={() => void handleAssignExistingPallet()}
                        >
                          <i className="bi bi-check2-circle" aria-hidden="true" />
                          Guardar
                        </button>
                        <button type="button" className="btn stock-box-form__btn stock-box-form__btn--cancel" onClick={cerrarFormPallet}>
                          <i className="bi bi-x-circle" aria-hidden="true" />
                          Cancelar
                        </button>
                      </div>
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>
        </>
      )}

      {!huecoSeleccionado && (
        <>
          <h5 className="mb-4">Mapa de Almacén</h5>
          {movePaletIdFromQuery !== null && (
            <div className="alert alert-info py-2 d-flex justify-content-between align-items-center">
              <span>
                Selecciona un hueco para mover el palé <strong>#{movePaletIdFromQuery}</strong>.
              </span>
              <button
                type="button"
                className="btn btn-sm btn-outline-secondary"
                onClick={() => navigate("/stock", { replace: true })}
                disabled={isMovingPallet}
              >
                Cancelar modo mover
              </button>
            </div>
          )}
          {actionMessage && <div className={`alert py-2 ${getActionAlertClass(actionMessage.type)}`}>{actionMessage.text}</div>}
          {mapError && <div className="alert alert-danger py-2">{mapError}</div>}
          {isLoadingMap ? (
            <div className="text-muted">Cargando mapa...</div>
          ) : (
            <div className="d-flex flex-column gap-1">
              {Array.from(pasillosMap.entries()).map(([pasilloId, detallesPasillo]) => (
                <Aisle
                  key={pasilloId}
                  pasilloId={pasilloId}
                  numero={detallesPasillo[0].pasillo.numero}
                  ubicaciones={detallesPasillo}
                  onHuecoClick={handleHuecoClick}
                />
              ))}
            </div>
          )}
        </>
      )}

      <SNSearchDeleteConfirmModal
        isOpen={confirmAction !== null}
        isLoading={isUnassigningPallet || isUnassigningBoxId !== null}
        title="Confirmar acción"
        message={
          confirmAction?.type === "box"
            ? `¿Seguro que quieres desasignar la caja ${confirmAction.cajaId} del palé ${confirmAction.paletId}?`
            : confirmAction?.type === "unassignPallet"
              ? `¿Seguro que quieres quitar el palé ${confirmAction.paletId} de esta ubicación?`
              : confirmAction?.type === "deletePallet"
              ? `¿Seguro que quieres eliminar el palé ${confirmAction.paletId}? Esta acción no se puede deshacer.`
              : ""
        }
        confirmLabel={confirmAction?.type === "unassignPallet" ? "Quitar palé" : "Eliminar"}
        cancelLabel="Cancelar"
        confirmVariant={confirmAction?.type === "unassignPallet" ? "primary" : "danger"}
        onCancel={() => {
          if (isUnassigningPallet || isUnassigningBoxId !== null) return;
          setConfirmAction(null);
        }}
        onConfirm={() => {
          if (!confirmAction) return;
          if (confirmAction.type === "box") {
            void handleUnassignBox(confirmAction.paletId, confirmAction.cajaId).finally(() => setConfirmAction(null));
            return;
          }
          if (confirmAction.type === "unassignPallet") {
            void handleUnassignPallet(confirmAction.paletId).finally(() => setConfirmAction(null));
            return;
          }
          void handleDeletePallet(confirmAction.paletId).finally(() => setConfirmAction(null));
        }}
      />
    </div>
  );
}
